# Generated by Django 2.0.4 on 2018-04-21 03:20

from django.db import migrations
import my_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20180421_0317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', my_auth.models.UserManager()),
            ],
        ),
    ]
